########
# SERIES
########

series:
  # The name of the organisation or entity that owns this series
  organisation: "Cape Town Aikido"
  # A live web address for the organisation
  url: "https://www.aiki.co.az/"
  # The default contact email address
  email: "craig@aiki.co.za"
  # The name of the series of books in this folder.
  name: "Aikido"
  # A one-liner about this series. Useful for Open Graph metadata.
  description: "Short books about Aikido, Aikido practice and Aikido teaching"
  # An image in /assets that stands for the series
  image: "publisher-logo.jpg"
  # For web navigation, the label for links to  the series homepage
  # For English sites, you can leave this as "Home".
  home-label: "Home"
  # For web navigation, the label for the navigation menu
  nav-label: "Contents"

########
# TITLES
########

## Metadata follows [Dublin Core](https://en.wikipedia.org/wiki/Dublin_Core#DCMI_Metadata_Terms)
## Custom fields added to standard DC terms: subtitle, publisher URL
## When listing files, exlude file extensions, and surround them in quotes especially if they contain only numbers.

works:
  - directory: "book"
    title: "Thoughts on Grading"
    subtitle: ""
    creator: "Craig Mason-Jones" # E.g. the author
    contributor: "" # E.g. other contributors
    subject: "Non-ficton" # E.g. BISAC terms (https://www.bisg.org/bisac/bisac-subject-codes) or BIC (http://editeur.dyndns.org/bic_categories)
    description: "Some thoughts on what to work on, when preparing to grade in Aikido, with an especial focus on the syllabus of the Aikido Federation of South Africa" # E.g. the blurb
    publisher: "aiki.co.za" # E.g. the publisher, imprint or brand name
    publisher-url: "https://www.aiki.co.za"
    date: "2017-03-20" # YYYY-MM-DD e.g. publication date
    modified: "2017-03-20" # YYYY-MM-DD e.g. date of last revision
    type: "Non-fiction" # e.g. Novel, Poetry, Memoir
    identifier: "" # e.g. ISBN or UUID
    source: "" # e.g. parent ISBN or ISTC
    language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
    relation: "" # e.g. other edition ISBN
    coverage: "" # e.g. geographic place or chronological time span
    rights: "All rights reserved.<br />No part of this book may be reproduced or transmitted in any form or by any electronic or mechanical means, including photocopying and recording, or any other information storage or retrieval system, without written permission from the publisher." # e.g. a copyright statement
    image: "cover.jpg"
    products: # Metadata for each product for this title (only use values that override parent metadata)
      print-pdf: 
        date: "2016-05-07" # YYYY-MM-DD e.g. publication or creation date
        format: "Print" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "0-1-titlepage"
          - "0-2-copyright"
          #- "0-3-contents"
          - "01"
          - "02"
        toc: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Chapter 1"
            file: "01"
            id: "hello-world"
          - label: "Chapter 2"
            file: "02"
            id: "goodbye-world"
            children: 
              - label: "Example child"
                file: "02"
                id: "example-id"
      web:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital online" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files: # To add a file to web navigation, give a file a value, e.g. 0-4-preface: "Preface"
          - "index": Cover
          - "0-1-titlepage"
          - "0-2-copyright": "Copyright"
          - "0-3-contents": "Contents"
          - "01": "Chapter One"
          - "02": "Chapter Two"
        nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Frontmatter"
            children:
              - label: "Cover"
                file: "index"
              - label: "Title page"
                file: "0-1-titlepage"
              - label: "Copyright"
                file: "0-2-copyright"
          - label: "Contents"
            file: "0-3-contents"
          - label: "Chapter One"
            file: "01"
            id: "1-hello-world"
          - label: "Chapter Two"
            file: "02"
            id: "2-goodbye-world"
            children: 
              - label: "Example child"
                file: "02"
                id: "example-id"
        start-page: "0-3-contents" # At which file should users start reading?
        contents-page: "0-3-contents" # Your contents-page file, if you have one.
        footer: "Powered by the <a href='http://electricbook.works'>Electric Book</a>" # Text that appears in the footer of the website. You can include HTML.
      epub:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "0-0-cover"
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "01"
          - "02"
      screen-pdf:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "0-0-cover"
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "01"
          - "02"
